module.exports = {
  User: require('./User'),
  UserAddress: require('./UserAddress'),
  Category: require('./Category'),
  Product: require('./Product'),
  ProductVariant: require('./ProductVariant'),
  ProductImage: require('./ProductImage'),
  Wishlist: require('./Wishlist'),
  Review: require('./Review'),
  Cart: require('./Cart'),
  CartItem: require('./CartItem'),
  Order: require('./Order'),
  OrderItem: require('./OrderItem'),
  OrderStatusHistory: require('./OrderStatusHistory'),
  InventoryLog: require('./InventoryLog'),
  InventoryMovement: require('./InventoryMovement'),
  Payment: require('./Payment'),
};
